general:
  motd:
    lineone: "#6#nTregmine!"
    linetwo: "#c#lTregmine?"
    maxplayers: 64
  life-log: true
  servername: Tregmine
  afk:
    #In seconds
    timeout: 900
    autoafk: 300
  economy:
    #Disable to use the /sell command instead
    minefortregs: true
  #DO NOT put a / at the end of the domain
  url: http://domain.lan
api:
  signing-key: your-strong-random-key-here
  port: 9192
db:
  url: jdbc:mysql://10.10.0.5:3306/tregmine_test?autoReconnect=true
  user: server
  password: server
support:
  user: tregmine.info@gmail.com
  password: will message you
  to:
    - email@emil.athisemail
#Worlds
worlds:
# Set enabled to true to run the worlds API
# Vanilla world is independent of the worlds API - Enable it to disable most of Tregmines features in a specialized vanilla world.
  vanillaworld: false
  special:
    # Before setting to true, move world to world_2 as with the nether and end
    newworld: false
    restrictnewworldtostaff: true
  enabled: false
  names:
#Rank Chat Colors
ranks:
  colors:
    tourist: "#f"
    settler: "#a"
    resident: "#2"
    donator: "#6"
    guardian: "#9"
    coder: "#5"
    builder: "#e"
    junior: "#c"
    senior: "#4"