name: TregmineHub
main: info.tregminehub.Tregmine
version: 1.0.0
website: https://www.tregmine.com
author: Ein Andersson, Emil Hernvall, Josh Morgan, James Sherlock, Rob Catron, Joe Notaro, Eric Rabil
description: Tregmine Plugin
loadbefore: [BlockLog,GameMagic]

commands:
  admins:
    description: Send a message to all active admins
    usage: /admins message
    aliases: a
  afk:
    description: Make your account AFK [Away From Keyboard]
    usage: /afk
  alert:
    description: Change your alerts (Cyan text in chat)
    usage: /alert
  allclear:
    description: Check if any blocks have been changed
    usage: /allclear [radius]
  back:
    description: Teleport to your previous location
    usage: /back
  guardians:
    description: Send a message to all active guardians
    usage: /guardians message
    aliases: g
  coders:
    description: Send a message to all online coders
    usage: /coders message
    aliases: c
  creative:
    description: Switch to creative mode (admins and builders only)
    usage: /creative
  survival:
    description: Switch to survival mode (admins and builders only)
    usage: /survival
  action:
    description: Indicates an action in chat
    usage: /action message
    aliases: me
  ban:
    description: Ban the specified player
    usage: /ban player
  blockhere:
    description: Create a block of dirt beneath your feet (admins and builders only)
    usage: /blockhere
  brush:
    description: Create a brush
    usage: /brush <material> <radius>
  cname:
    description: Change your name and color (admin only)
    usage: /cname color new_name
  channel:
    description: Change to the specified channel
    usage: /channel channel_name
  channelview:
    description: View all channels whilst in one channel (admins)
    usage: /channelview <on/off>
  createmob:
    description: Create mobs from empty air (admin only)
    usage: /createmob mob_type amount [name]
  fill:
    description: Fill, replace and copy blocks using a wooden spade (admins and builders only)
    usage: /fill
  fly:
    description: Fly, Toggles flying using the Player Flags system
    usage: /fly
  force:
    description: Force someone into a channel
    usage: /force player channel
  forceblock:
    description: Stop people forcing you into channels
    usage: /forceblock <on/off/status>
  freeze:
    description: Freeze a specified player
    usage: /freeze <player>
  gamemode:
    description: Change a players gamemode (admin only)
    usage: /gamemode <mode>
  give:
    description: Give a user an item (admin only)
    usage: /give player item amount data
  ignore:
    description: Ignore a player (not staff)
    usage: /ignore <add/remove> <player_name> or /ignore <list>
  invlog:
    description: Toggle inventory logging display
    usage: /invlog <on/off/status>
  item:
    description: Spawn an item
    usage: /item item amount data (admin only)
  keyword:
    description: Set your keyword
    usage: /keyword keyword
  kick:
    description: Kick a player (admins and guardians only)
    usage: /kick player
  kill:
    description: Kill a player (admins only)
    usage: /kill player
  lockdown:
    description: Lock the server (admins only)
    usage: /lockdown on|off
  mail:
    description: Send mail to players, offline or online
    usage: /mail read|send|delete|total|tbt
  msg:
    description: Message another player
    usage: /msg player message
    aliases: [m, tell]
  newspawn:
    description: Temporarily change the spawn on this map (admin only)
    usage: /newspawn
  nuke:
    description: Kill all mobs on this map (admins and guardians only)
    usage: /nuke
  pos:
    description: Prints your position to the console
    usage: /pos
  promote:
    description: Promotes a user
    usage: /promote
  property:
    description: Updates a player property (admin only)
    usage: /property <player> <key> <value>
  quitmessage:
    description: Set a quit message (donators only)
    usage: /quitmessage <message>
  regeneratechunk:
    description: Regenerate the current chunk (admin only)
    usage: /regeneratechunk
  remitems:
    description: remove all items in the specified radius
    usage: /remitems radius
  reply:
    description: Reply to the last message you received
    usage: /reply <message>
    aliases: [r]
  report:
    description: Adds a report to the players record
    usage: /report player message
  resetlore:
    description: Reset a lore for an item accidentally flagged as creative or spawned [IM_NOT_ERIC OR OPS ONLY]
    usage: /resetlore
  rname:
    description: Resets the players nickname
    usage: /rname
  say:
    description: Speak as god (admins only)
    usage: /say message
  seen:
    description: Check a players last login
    usage: /seen player
  sendback:
    description: Send a player to their previous location (admins only)
    usage: /sendback player
  sendto:
    description: Send a player to another world (admins only)
    usage: /sendto player world
  setbiome:
    description: Set the selected area's biome
    usage: /setbiome biome 
  setspawner:
    description: Change a mob spawners type (admins only)
    usage: /setspawner
  spawn:
    description: Go back to spawn
    usage: /spawn
  summon:
    description: Summon a player to your location
    usage: /summon player
    aliases: s
  support:
    description: Send support message
    usage: /support message
    aliases: sup
  staffbook:
    description: Gives the guidelines for staff to follow
    usage: /staffbook
  staffnews:
    description: Add a message to the staff message board
    usage: /staffnews <message>
  testfill:
    description: Like fill, but with fake blocks (admins and builders only)
    usage: /testfill
  tp:
    description: Teleport to a player
    usage: /tp player
  ttps:
    description: Get the T-TPS of the server
    usage: /ttps
  tpshield:
    description: Prevent players from teleporting to you (donators only)
    usage: /tpshield
    aliases: tpblock
  tpto:
    description: Teleport to specified coordinates (admin only)
    usage: /tpto x y z
  time:
    description: Change the time of day (donators only)
    usage: /time day|night|normal
  update:
    description: See what was last updated!
    usage: /update [version number]
  undercoverboss:
    description: Go undercover!
    usage: /undercoverboss <guardian, donator, resident>
  vanish:
    description: Become invisible (admin only)
    usage: /vanish <on|off>
  wallet:
    description: Modify your wallet
    usage: /wallet
  warn:
    description: Warn a user (guardian and admin only)
    usage: /warn <hard|soft> <player> <message>
  weather:
    description: Change weather (donators only)
    usage: /weather <downfall or clear>
  who:
    description: Look up information about a player
    usage: /who <player>
  lottery:
    description: Type /lottery for additional info.
    usage: /lottery
  head:
    description: Receive a specified player's head.
    usage: /head <player>
  hide:
    description: Hide logon message
    usage: /hide
  watchchunks:
    description: Informs the player when they load new and old chunks without spam
    usage: /watchchunks on/off/status
  chunkcount:
    description: See number of chunks in each world
    usage: /chunkcount
